# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#     password: 1234

app:
#  userMap:
#    user: "ENC(2m1OYeVuB0jG3gVX/tJkPJ0O/2cE6dwatl+VhMOUAsdKIe56MS9SSH6ngmfn/9u3)"
#    admin: "ENC(Qg5Sh/zpItt1MevUIUVakw==)"
#    guest: "ENC(Qg5Sh/zpItt1MevUIUVakw==)"
  key: "10"

