# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#     password: 1234

app:
#  userMap:
#    user: "ENC(2m1OYeVuB0jG3gVX/tJkPJ0O/2cE6dwatl+VhMOUAsdKIe56MS9SSH6ngmfn/9u3)"
#    admin: "ENC(Qg5Sh/zpItt1MevUIUVakw==)"
#    guest: "ENC(Qg5Sh/zpItt1MevUIUVakw==)"
  key: "10"

  discountMap:
    NEW_ARRIVALS: "Sports"
    STOCK_CLEARING: "Shoes"
    FESTIVE_SALE: "Electronics"

  productCategory:
#    Category: SubCategory
    Electronics: "Tv, Mobile, Gaming Console, Washing Machine, Microwave, Refrigerator"
    Shoes: "Sports Shoes, Casual Shoes, Formal Shoes"
    Sports: "Cricket, Football, Basketball, Volleyball, Table Tennis, Badminton, Snooker"

  productMap:
#    Sports
    Cricket:
      - name: SG Bat
        price: 3500
        description: Premium quality cricket bat.
      - name: Kookaburra Ball
        price: 600
        description: Professional grade cricket ball.
      - name: Adidas Cricket Shoes
        price: 4000
        description: High-performance cricket shoes.
      - name: GM Gloves
        price: 1200
        description: Durable cricket gloves with excellent grip.
      - name: SS Helmet
        price: 2500
        description: Protective cricket helmet.
      - name: MRF Pads
        price: 1500
        description: Comfortable cricket pads for safety.
      - name: DSC Stumps
        price: 1000
        description: Set of three cricket stumps.
      - name: Puma Kit Bag
        price: 3500
        description: Spacious kit bag for carrying cricket equipment.
    Football:
      - name: Adidas Football
        price: 1500
        description: High-performance football used in professional matches.
      - name: Nike Shin Guards
        price: 800
        description: Protective shin guards for football players.
      - name: Puma Football Shoes
        price: 3500
        description: Comfortable and durable football shoes.
      - name: Adidas Jersey
        price: 2000
        description: Official team jersey.
      - name: Nike Goalkeeper Gloves
        price: 2500
        description: High-grip goalkeeper gloves.
      - name: Puma Football Socks
        price: 500
        description: Comfortable and breathable football socks.
      - name: Adidas Training Cones
        price: 1200
        description: Set of 20 training cones for drills.
      - name: Nike Training Bibs
        price: 1000
        description: Lightweight training bibs for practice sessions.
    Basketball:
      - name: Spalding Basketball
        price: 2000
        description: Official NBA size and weight basketball.
      - name: Nike Basketball Shoes
        price: 4500
        description: High-performance shoes designed for basketball.
      - name: Wilson Net
        price: 1500
        description: Durable basketball net for outdoor courts.
      - name: Adidas Jersey
        price: 2200
        description: Official team jersey.
      - name: Nike Arm Sleeve
        price: 700
        description: Compression arm sleeve for basketball players.
      - name: Spalding Air Pump
        price: 800
        description: Portable air pump for inflating basketballs.
      - name: Gatorade Bottle
        price: 300
        description: Reusable water bottle.
      - name: Under Armour Headband
        price: 500
        description: Sweat-absorbent headband for basketball players.
    Volleyball:
      - name: Mikasa Volleyball
        price: 1200
        description: Professional beach volleyball.
      - name: Volleyball Net
        price: 1500
        description: Durable net suitable for outdoor and indoor volleyball games.
      - name: Adidas Volleyball Shoes
        price: 3800
        description: High-grip shoes for volleyball players.
      - name: Nike Knee Pads
        price: 900
        description: Protective knee pads for volleyball.
      - name: Wilson Volleyball Bag
        price: 2500
        description: Spacious bag for carrying volleyball gear.
      - name: Mizuno Elbow Pads
        price: 1000
        description: Elbow pads for protection during games.
      - name: Mikasa Whistle
        price: 300
        description: High-pitched whistle for referees.
      - name: Under Armour Water Bottle
        price: 500
        description: Insulated water bottle for hydration during games.
    Table Tennis:
      - name: Stiga Table Tennis Bat
        price: 700
        description: High-quality table tennis bat for advanced players.
      - name: Butterfly Table Tennis Ball
        price: 100
        description: Premium 3-star table tennis balls.
      - name: Cornilleau Table
        price: 12000
        description: Professional-grade table tennis table.
      - name: Stiga Net
        price: 800
        description: Durable table tennis net.
      - name: Donic Bat Cover
        price: 300
        description: Protective cover for table tennis bat.
      - name: Joola Shoes
        price: 1800
        description: Lightweight shoes for quick movement on the court.
      - name: Andro Bat Rubber
        price: 1200
        description: High-spin bat rubber for table tennis.
      - name: Tenergy Grip Tape
        price: 400
        description: Non-slip grip tape for table tennis bats.
    Badminton:
      - name: Yonex Badminton Racquet
        price: 1800
        description: Lightweight and durable badminton racquet.
      - name: Li-Ning Shuttlecock
        price: 500
        description: High-quality shuttlecock for competitive play.
      - name: Victor Badminton Shoes
        price: 3000
        description: High-performance shoes for badminton.
      - name: Yonex String
        price: 700
        description: Durable string for badminton racquets.
      - name: Li-Ning Grip
        price: 300
        description: Comfortable grip for racquet handles.
      - name: Yonex Kit Bag
        price: 2500
        description: Spacious bag for carrying badminton equipment.
      - name: Babolat Wristbands
        price: 200
        description: Sweat-absorbent wristbands.
      - name: Carlton Knee Support
        price: 900
        description: Knee support for badminton players.
    Snooker:
      - name: Riley Snooker Cue
        price: 3000
        description: Professional-grade snooker cue.
      - name: Aramith Snooker Balls
        price: 2500
        description: Tournament-level snooker balls.
      - name: Riley Snooker Table
        price: 150000
        description: Full-size professional snooker table.
      - name: Kamui Chalk
        price: 300
        description: High-quality cue chalk for snooker.
      - name: Peradon Cue Case
        price: 2000
        description: Protective case for snooker cue.
      - name: Triangle Rack
        price: 700
        description: Wooden triangle rack for setting up balls.
      - name: Riley Snooker Glove
        price: 500
        description: Glove for smooth cue control.
      - name: Table Brush
        price: 600
        description: Brush for maintaining the snooker table cloth.
#    Electronics
    Tv:
      - name: LG OLED TV
        price: 120000
        description: 55-inch OLED TV with 4K resolution.
      - name: Sony Bravia
        price: 95000
        description: 50-inch LED TV with smart features.
      - name: Samsung QLED
        price: 140000
        description: 65-inch QLED TV with HDR10+.
      - name: Panasonic Viera
        price: 85000
        description: 50-inch LED TV with IPS panel.
      - name: TCL Roku TV
        price: 45000
        description: 40-inch smart TV with built-in Roku.
      - name: Philips Ambilight
        price: 125000
        description: 55-inch TV with Ambilight technology.
      - name: Vizio SmartCast
        price: 70000
        description: 55-inch 4K TV with Chromecast built-in.
      - name: Hisense ULED
        price: 60000
        description: 50-inch ULED TV with Dolby Vision.
    Mobile:
      - name: iPhone 14 Pro
        price: 120000
        description: Apple's latest smartphone with ProMotion display.
      - name: Samsung Galaxy S23
        price: 105000
        description: High-performance Android smartphone with 108MP camera.
      - name: Google Pixel 7
        price: 85000
        description: Google’s flagship smartphone with pure Android experience.
      - name: OnePlus 11
        price: 75000
        description: High-end smartphone with 120Hz display and fast charging.
      - name: Xiaomi Mi 13
        price: 50000
        description: Affordable smartphone with high-end specs.
      - name: Sony Xperia 1 V
        price: 95000
        description: Smartphone with 4K OLED display and professional camera features.
      - name: Oppo Find X6 Pro
        price: 90000
        description: Premium smartphone with advanced camera system.
      - name: Huawei P60 Pro
        price: 95000
        description: Flagship smartphone with powerful AI features.
    GamingConsole:
      - name: PlayStation 5
        price: 60000
        description: Sony's latest gaming console with ray tracing and SSD storage.
      - name: Xbox Series X
        price: 55000
        description: Microsoft’s powerful console with 4K gaming and Game Pass.
      - name: Nintendo Switch OLED
        price: 35000
        description: Portable gaming console with OLED display.
      - name: PlayStation 4 Pro
        price: 30000
        description: Previous-gen console with 4K support.
      - name: Xbox Series S
        price: 30000
        description: Budget-friendly console with 1440p gaming.
      - name: Nintendo Switch Lite
        price: 20000
        description: Portable gaming console for handheld play.
      - name: Steam Deck
        price: 45000
        description: Portable PC gaming console by Valve.
      - name: Xbox One X
        price: 35000
        description: Older Xbox console with 4K capabilities.
    WashingMachine:
      - name: LG Front Load
        price: 35000
        description: 8kg front load washing machine with steam technology.
      - name: Samsung Top Load
        price: 25000
        description: 6.5kg top load washing machine with inverter technology.
      - name: Bosch Front Load
        price: 40000
        description: 7kg front load washing machine with EcoSilence drive.
      - name: Whirlpool Semi-Automatic
        price: 15000
        description: 7.5kg semi-automatic washing machine.
      - name: IFB Front Load
        price: 32000
        description: 6.5kg front load washing machine with in-built heater.
      - name: Haier Top Load
        price: 22000
        description: 7kg top load washing machine with self-clean technology.
      - name: Panasonic Front Load
        price: 38000
        description: 8kg front load washing machine with smart inverter.
      - name: Godrej Semi-Automatic
        price: 18000
        description: 7kg semi-automatic washing machine with rust-proof body.
    Microwave:
      - name: LG Convection
        price: 20000
        description: 32L convection microwave oven with smart inverter.
      - name: Samsung Grill
        price: 15000
        description: 28L grill microwave with auto-cook menus.
      - name: IFB Solo
        price: 10000
        description: 20L solo microwave with touch keypad.
      - name: Panasonic Inverter
        price: 18000
        description: 30L microwave with inverter technology.
      - name: Morphy Richards Convection
        price: 12000
        description: 25L convection microwave with 200 auto-cook menus.
      - name: Bajaj Grill
        price: 8000
        description: 20L grill microwave with timer function.
      - name: Whirlpool Convection
        price: 16000
        description: 23L convection microwave with multi-stage cooking.
      - name: Godrej Solo
        price: 9000
        description: 22L solo microwave with defrost function.
    Refrigerator:
      - name: LG Double Door
        price: 45000
        description: 260L double door refrigerator with smart inverter compressor.
      - name: Samsung Side by Side
        price: 80000
        description: 600L side-by-side refrigerator with water dispenser.
      - name: Whirlpool Triple Door
        price: 55000
        description: 340L triple door refrigerator with auto defrost.
      - name: Haier Bottom Mount
        price: 48000
        description: 320L bottom mount refrigerator with 1-hour icing technology.
      - name: Godrej Single Door
        price: 25000
        description: 190L single door refrigerator with direct cool technology.
      - name: Panasonic Multi-Door
        price: 60000
        description: 450L multi-door refrigerator with inverter technology.
      - name: Bosch French Door
        price: 90000
        description: 500L French door refrigerator with VitaFresh technology.
      - name: Videocon Double Door
        price: 40000
        description: 300L double door refrigerator with energy-efficient cooling.
#    Shoes
    SportsShoes:
      - name: Nike Air Zoom
        price: 10000
        description: Lightweight running shoes with responsive cushioning.
      - name: Adidas Ultraboost
        price: 12000
        description: High-performance running shoes with energy return.
      - name: Puma Running Shoes
        price: 8000
        description: Durable shoes designed for long-distance running.
      - name: Reebok CrossFit
        price: 9000
        description: Versatile shoes for cross-training and gym workouts.
      - name: Asics Gel-Kayano
        price: 11000
        description: Stability running shoes with gel cushioning.
      - name: Under Armour Charged
        price: 9500
        description: Running shoes with dual-layer charged cushioning.
      - name: New Balance Fresh Foam
        price: 10500
        description: Comfortable running shoes with fresh foam midsole.
      - name: Skechers GoRun
        price: 8500
        description: Flexible and lightweight shoes for running.
    CasualShoes:
      - name: Vans Old Skool
        price: 5000
        description: Classic skate shoes with iconic side stripe.
      - name: Converse Chuck Taylor
        price: 4500
        description: Timeless high-top sneakers.
      - name: Adidas Stan Smith
        price: 7000
        description: Iconic low-top sneakers with a minimalist design.
      - name: Puma Suede Classic
        price: 6000
        description: Retro sneakers with a suede upper.
      - name: Nike Air Force 1
        price: 8000
        description: Classic sneakers with a thick sole and perforated toe box.
      - name: New Balance 574
        price: 6500
        description: Comfortable and stylish casual shoes.
      - name: Skechers Slip-On
        price: 5500
        description: Easy-to-wear slip-on shoes with a cushioned insole.
      - name: Toms Alpargata
        price: 4000
        description: Lightweight and breathable casual shoes.
    FormalShoes:
      - name: Clarks Oxford
        price: 9000
        description: Premium leather oxford shoes.
      - name: Allen Edmonds Derby
        price: 12000
        description: High-quality derby shoes with a sleek design.
      - name: Johnston & Murphy Loafers
        price: 8000
        description: Classic leather loafers for formal occasions.
      - name: Cole Haan Monk Strap
        price: 10000
        description: Elegant monk strap shoes with a polished finish.
      - name: Hugo Boss Brogues
        price: 11000
        description: Stylish brogue shoes with wingtip detailing.
      - name: Kenneth Cole Dress Boots
        price: 9500
        description: Sleek dress
